# Generated by Django 5.2.17 on 2026-09-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['nom'], 'permissions': [('acceder_tableau_bord', 'Peut accéder au tableau de bord'), ('exporter_stock', 'Peut exporter les données de stock')], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
    ]
