# Generated by Django 5.2.17 on 2026-09-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_produit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouvement',
            options={'ordering': ['-date_mouvement', '-id'], 'verbose_name': 'Mouvement', 'verbose_name_plural': 'Mouvements'},
        ),
    ]
