# Generated by Django 5.2.17 on 2026-09-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_mouvement_destination_mouvement_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='delai_jours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='unite',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
